vim.cmd([[nnoremap <C-j> :lua vim.diagnostic.goto_next()<cr>]])
vim.cmd([[nnoremap <C-k> :lua vim.diagnostic.goto_prev()<cr>]])
vim.cmd([[nnoremap <C-w> :lua vim.lsp.buf.format()<cr>:w<cr>]])
vim.cmd([[nnoremap <C-space> :lua vim.lsp.buf.hover()<cr>]])
vim.cmd([[nnoremap <leader>d :lua vim.lsp.buf.definition()<cr>]])
vim.cmd([[nnoremap <leader>a :lua vim.lsp.buf.code_action()<cr>]])
vim.cmd([[nnoremap <leader>r :lua vim.lsp.buf.rename()<cr>]])
vim.cmd([[nnoremap <leader>s :lua vim.lsp.buf.signature_help()<cr>]])
